# Generated by Django 5.2.5 on 2025-09-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_body_post_is_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
