# Generated by Django 4.2.23 on 2025-07-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='運動名')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='回数/時間')),
                ('level', models.IntegerField(choices=[(1, 'レベル1'), (2, 'レベル2'), (3, 'レベル3'), (4, 'レベル4'), (5, 'レベル5')], verbose_name='対象レベル')),
            ],
        ),
    ]
