# Generated by Django 4.2.23 on 2025-07-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_remove_exercise_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255, verbose_name='運動名'),
        ),
    ]
