# Generated by Django 5.2.6 on 2025-09-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_exercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='スペシャル運動かどうか'),
        ),
    ]
