# Generated by Django 5.2.6 on 2025-09-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimer',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
