# Generated by Django 5.2.6 on 2025-09-11 22:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_exercise_name'),
        ('exercise_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='time',
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='performed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
    ]
