# Generated by Django 5.2.6 on 2025-09-13 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_logs', '0002_remove_exerciselog_date_remove_exerciselog_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
