# Generated by Django 5.2.6 on 2025-09-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_logs', '0003_exerciselog_date_exerciselog_time'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
