# Generated by Django 5.2.6 on 2025-09-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_logs', '0004_exerciselog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='from_gacha',
            field=models.BooleanField(default=False),
        ),
    ]
